version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver_bank
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SeuSenhaF0rte!"  # Altere para uma senha forte
    volumes:
      - bank_volume:/var/opt/mssql
    restart: unless-stopped

volumes:
  bank_volume:
    name: bank_volume