CREATE TABLE TB_USER (
    id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    name NVARCHAR(255) NOT NULL,
    email NVARCHAR(255) NOT NULL,
    document NVARCHAR(50) NOT NULL,
    active BIT NOT NULL DEFAULT 1
);